openapi: 3.0.0
info:
  title: Cytric NFT Rest API  - OpenAPI 3.0
  version: 1.0.0
  description: Cytric NFT Backend
  contact:
    name: Anderson Osayerie
    email: osayerieanderson@gmail.com
    url: https://andemosa.tech
paths:
  /api/nfts:
    post:
      tags:
        - NFT
      summary: store a new NFT
      description: This endpoint is used when a user wants to store a new NFT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreNFTSchema"
      responses:
        "201":
          description: NFT stored successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreNFTResponse"
        "400":
          description: Bad request
        "409":
          description: Conflict
    get:
      tags:
        - NFT
      summary: Return a list of nfts
      description: This endpoint is used to return a list of nfts owned by a wallet
        address. It accepts query filters.
      parameters:
        - in: query
          name: address
          schema:
            type: string
            default: null
          description: The wallet address for which nfts should be gotten
          required: true
      responses:
        "200":
          description: Returns a list of nfts for the wallet address
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetNFTsResponse"
        "400":
          description: Bad request
  "/api/nfts/{id}":
    get:
      tags:
        - NFT
      summary: Gets the data for an NFT
      description: This endpoint is used to retrieve data stored under an nft id.
      parameters:
        - name: id
          in: path
          description: The id of the nft
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetNFTDataResponse"
        "400":
          description: Bad request
        "404":
          description: NFT not found
components:
  schemas:
    StoreNFTSchema:
      type: object
      additionalProperties: false
      required:
        - name
        - description
        - address
        - id
        - logo
      properties:
        name:
          type: string
          default: null
        description:
          type: string
          default: null
        address:
          type: string
          default: null
        id:
          type: number
          default: null
        logo:
          type: string
          default: null
    StoreNFTResponse:
      type: object
      properties:
        _id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        description:
          type: string
        logo:
          type: string
        address:
          type: string
        id:
          type: number
    GetNFTsResponse:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
          createdAt:
            type: string
          updatedAt:
            type: string
          name:
            type: string
          description:
            type: string
          logo:
            type: string
          address:
            type: string
          id:
            type: number
    GetNFTDataResponse:
      type: object
      properties:
        _id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        description:
          type: string
        logo:
          type: string
        address:
          type: string
        id:
          type: number
tags:
  - name: NFT
    description: The NFT API provides endpoints for managing NFTs, including
      storing, retrieving wallet address's NFTs.
